name: taxi_rahmati
description: App for taking notes for taxi rides.

publish_to: 'none'

version: 1.1.2+7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0 # dependency injection
  flutter_bloc: ^8.0.1 # block for state management
  equatable: ^2.0.3 # value equality
  dartz: ^0.10.1 # functional programming
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.4 # "
  shared_preferences: ^2.0.15 # local cache
  decimal: ^2.2.0 # for currency
  uuid: ^3.0.6 # id generation
  plugin_platform_interface: ^2.1.2
  enum_to_string: ^2.0.1
  intl: ^0.17.0 # dateFormat
  google_fonts: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  currency_text_input_formatter: ^2.1.5
  printing: ^5.9.1
  flutter_screenutil: ^5.5.3+2 # ui resolution 
  quiver: ^3.1.0 # list split
  flutter_typeahead: ^4.0.0
  rflutter_alert: ^2.0.4 # popup

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11 # for mockito

flutter:
  uses-material-design: true
  fonts:
    - family: Kodchasan
      fonts:
        - asset: fonts/kodchasan/Kodchasan-ExtraLight.ttf
          weight: 200
        - asset: fonts/kodchasan/Kodchasan-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/kodchasan/Kodchasan-Light.ttf
          weight: 300
        - asset: fonts/kodchasan/Kodchasan-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/kodchasan/Kodchasan-Regular.ttf
          weight: 400
        - asset: fonts/kodchasan/Kodchasan-Medium.ttf
          weight: 500
        - asset: fonts/kodchasan/Kodchasan-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/kodchasan/Kodchasan-SemiBold.ttf
          weight: 600
        - asset: fonts/kodchasan/Kodchasan-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/kodchasan/Kodchasan-Bold.ttf
          weight: 700
        - asset: fonts/kodchasan/Kodchasan-BoldItalic.ttf
          weight: 700
          style: italic